services:
  - type: web
    name: ayush-chatbot-backend
    runtime: python3
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn chatbot:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false

  - type: web
    name: ayush-chatbot-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: ayush-chatbot-backend
          property: host